# Generated by Django 5.0.6 on 2024-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='crime_status',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved')], default='approved'),
        ),
    ]
