# Generated by Django 5.0.6 on 2024-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0002_alter_report_crime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
